GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO my_budget_user;
GRANT USAGE ON SCHEMA public TO my_budget_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO my_budget_user;
GRANT CREATE ON SCHEMA public TO my_budget_user;


